// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usnkfgchcyrobingibqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbmtmZ2NoY3lyb2JpbmdpYnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0ODExNjUsImV4cCI6MjA1NTA1NzE2NX0.IjFa-in8h19jHJHTIaavfU38q7HuunQZv11eUduN2lI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);